In [10]:
# importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style('whitegrid')

In [13]:
# Allow display of all columns
pd.set_option('display.max_columns', None)

# loading the data
nmes_df = pd.read_csv("nmes.txt", sep="\t", header=0)
nmes_df.head(50)

,PIDX,LASTAGE,MALE,RACE3,eversmk,current,former,AGESMOKE,CIGSSMOK,CIGSADAY,AGESTOP,packyears,yearsince,INCALPER,TOTALEXP,lc5,chd5,beltuse,educate,marital,SREGION,POVSTALB
0,20843014,80,0,3,0,.,0,.,.,.,.,0,0,5805.555102,297.75,0,1,3,4,2,1,1
1,20833013,78,0,3,.,.,.,.,.,.,.,.,.,7428.738855,451.57,0,0,3,3,2,1,4
2,20832010,80,1,3,1,1,0,21,10,10,.,30,0,8220.839822,1368.76,0,1,1,3,3,1,3
3,20829011,71,1,3,1,0,1,16,.,.,46,.,25,4857.094656,1205.32,0,0,3,3,1,1,5
4,20829024,69,0,3,.,.,.,.,.,.,.,.,.,4808.212619,662.02,0,0,.,3,1,1,5
5,20827015,70,0,3,.,.,.,.,.,.,.,.,.,5663.136054,286.97,0,0,.,1,2,1,4
6,20825018,60,0,3,1,0,1,30,20,.,38,9,22,12289.275970,795.00,0,0,3,2,5,1,5
7,20821016,82,0,3,1,0,1,16,2,.,35,2,47,8790.163608,1627.09,0,0,3,3,5,1,4
8,20820013,58,1,3,.,.,.,.,.,.,.,.,.,14242.308460,0.00,0,0,.,1,1,1,3
9,20820026,46,0,3,.,.,.,.,.,.,.,.,.,15434.187510,110.00,0,0,.,1,1,1,3
10,20818017,61,1,3,1,0,1,.,.,.,.,.,.,14159.751110,3306.50,0,1,1,1,3,1,5
11,20815017,82,1,1,1,0,1,15,.,.,40,.,42,3780.906462,0.00,0,0,2,4,1,1,4
12,20815020,79,0,1,0,.,0,.,.,.,.,0,0,4750.479403,18422.05,0,0,1,4,1,1,4
13,20814014,67,1,1,.,.,.,.,.,.,.,.,.,4149.210398,0.00,0,0,.,4,1,1,1
14,20814027,61,0,1,.,.,.,.,.,.,.,.,.,5967.641886,248.00,0,0,.,4,1,1,1
15,20813024,55,0,1,1,1,0,16,10,10,.,20,0,9027.188295,705.00,0,0,2,3,2,1,1
16,20812018,80,1,1,1,.,.,16,.,.,.,.,.,4196.344184,794.36,0,0,3,4,5,1,3
17,20811015,58,1,2,1,0,1,17,4,.,50,6.8,8,6509.762844,0.00,0,0,3,3,1,1,5
18,20811028,57,0,2,0,.,0,.,.,.,.,0,0,4742.836092,75.00,0,0,3,3,1,1,5
19,20807013,67,1,3,1,0,1,20,20,.,60,41,7,8574.218676,1616.01,0,0,3,3,3,1,4
20,20806019,62,1,2,.,.,.,.,.,.,.,.,.,6895.030269,3431.44,0,0,.,4,2,1,1
21,20802017,68,1,1,0,.,0,.,.,.,.,0,0,3620.282978,20.00,0,0,1,4,1,1,3
22,20802020,61,0,1,.,.,.,.,.,.,.,.,.,5129.563263,330.96,0,0,.,4,1,1,3
23,20798015,65,1,1,0,.,0,.,.,.,.,0,0,4708.924109,351.52,0,0,2,4,1,1,1
24,20796018,58,0,1,.,.,.,.,.,.,.,.,.,7589.548665,85.00,0,0,.,3,4,1,4
25,20795028,51,0,1,1,1,0,15,.,20,.,37,0,3329.306213,4141.50,0,0,2,3,4,1,5
26,20793019,59,1,1,.,.,.,.,.,.,.,.,.,2936.256261,70.00,0,0,3,3,2,1,5
27,20792016,56,0,1,.,.,.,.,.,.,.,.,.,8431.898566,4340.22,0,0,.,3,3,1,1
28,20790010,77,0,1,.,.,.,.,.,.,.,.,.,4512.620590,155.00,0,0,3,4,2,1,4
29,20785014,44,1,1,0,.,0,.,.,.,.,0,0,6928.582776,0.00,0,0,3,4,1,1,2
30,20785027,43,0,1,.,.,.,.,.,.,.,.,.,3805.396750,0.00,0,0,.,3,1,1,2
31,20780064,42,1,1,1,1,0,17,20,25,.,26,0,7439.176019,380.00,0,0,2,3,3,1,5
32,20777010,79,1,1,1,0,1,21,26,.,71,66.3,8,3875.873946,137.50,0,0,3,3,1,1,3
33,20777023,75,0,1,0,.,0,.,.,.,.,0,0,3589.127270,85.00,0,0,3,3,1,1,3
34,20775013,47,0,1,0,.,0,.,.,.,.,0,0,3458.437071,7537.57,0,0,2,4,5,1,3
35,20773017,51,0,1,0,.,0,.,.,.,.,0,0,4277.330734,43.39,0,0,3,4,1,1,2
36,20773062,61,1,1,1,0,1,20,1,.,30,0.55,31,10808.274030,52883.99,0,1,1,4,5,1,1
37,20770018,65,1,1,1,0,1,17,15,.,45,21.75,20,4291.930997,0.00,0,0,3,3,2,1,4
38,20767019,72,1,1,.,.,.,.,.,.,.,.,.,3621.121298,18168.18,0,0,3,3,1,1,3
39,20767022,58,0,1,.,.,.,.,.,.,.,.,.,5657.909513,186.00,0,0,.,3,1,1,3
40,20763016,62,1,1,0,.,0,.,.,.,.,0,0,4145.518371,119.00,0,0,3,4,1,1,4
41,20763029,45,0,1,0,.,0,.,.,.,.,0,0,6139.058047,717.34,0,0,3,4,1,1,4
42,20761023,44,0,1,.,.,.,.,.,.,.,.,.,11342.014330,291.60,0,0,.,4,3,1,1
43,20759014,42,0,1,0,.,0,.,.,.,.,0,0,5566.204498,364.00,0,0,2,3,1,1,4
44,20759027,42,1,1,0,.,0,.,.,.,.,0,0,5831.604275,0.00,0,0,2,1,1,1,4
45,20758011,71,1,1,.,.,.,.,.,.,.,.,.,4492.281010,20.00,0,0,.,4,1,1,1
46,20757018,70,1,3,1,0,1,21,18,.,60,36,10,4657.575550,588.84,1,0,3,3,1,1,5
47,20757021,70,0,3,.,.,.,.,.,.,.,.,.,4801.199586,0.00,0,0,3,4,1,1,5
48,20757034,41,0,3,1,1,0,16,10,18,.,13,0,3933.455968,113.30,0,0,3,3,5,1,5
49,20756014,55,1,3,1,1,0,10,60,3,.,138,0,11061.096030,501.80,0,0,1,4,1,1,4

In [14]:
nmes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13648 entries, 0 to 13647
Data columns (total 22 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   PIDX       13648 non-null  int64
 1   LASTAGE    13648 non-null  int64
 2   MALE       13648 non-null  int64
 3   RACE3      13648 non-null  int64
 4   eversmk    13648 non-null  object
 5   current    13648 non-null  object
 6   former     13648 non-null  object
 7   AGESMOKE   13648 non-null  object
 8   CIGSSMOK   13648 non-null  object
 9   CIGSADAY   13648 non-null  object
 10  AGESTOP    13648 non-null  object
 11  packyears  13648 non-null  object
 12  yearsince  13648 non-null  object
 13  INCALPER   13648 non-null  float64
 14  TOTALEXP   13648 non-null  float64
 15  lc5        13648 non-null  int64
 16  chd5       13648 non-null  int64
 17  beltuse    13648 non-null  object
 18  educate    13648 non-null  int64
 19  marital    13648 non-null  object
 20  SREGION    13648 non-null  int64
 21  POVSTALB   13648 non-null  object
dtypes: float64(2), int64(8), object(12)
memory usage: 2.3+ MB